Repository sasalx/ProCatalog, pull requests merged in 2018-12, with the labels that each got.

#1 DatabaseOperations class created
  .gitignore
  .idea/dataSources/fc0cbe50-7738-48f1-ad1f-3efa85335ce3/storage_v2/_src_/schema/main.uQUzAA.meta
  procatalog.db
  src/DatabaseOperations.java
Labels: Database

#2 List Back-end
  src/DataList.java
Labels: Back-End

#3 All Collections method added
  src/DatabaseOperations.java
Labels: Database

#4 Add new collection with column specification
  src/DatabaseOperations.java
Labels: Database

#7 Search functionality added
  procatalog.db
  src/AllCollectionsPage.java
  src/CustomFrame.java
  src/Main.java
Labels: Front-End

#8 Fetch all columns method added
  src/AllCollectionsPage.java
  src/DataList.java
  src/DatabaseOperations.java
Labels: Front-End

#12 Button Functionalities
  procatalog.db
  src/AllCollectionsPage.java
  src/CustomFrame.java
  src/DataList.java
  src/DatabaseOperations.java
Labels: Back-End, Front-End

#15 Merge fix
  src/AllCollectionsPage.java
  src/DatabaseOperations.java
  src/Main.java
Labels: Back-End, Front-End

#16 Small Bug Fixes
  procatalog.db
  src/AllCollectionsPage.java
Labels: enhancement

#17 Beta Version Release
  procatalog.db
  src/AllCollectionsPage.java
  src/CustomFrame.java
  src/DataList.java
  src/DatabaseOperations.java
  src/Main.java
Labels: Back-End, Database, Front-End
